### ISSUE TITLE
Incompatible with Blue Skies 1.18.2

### ISSUE THREAD

**Issue by WelpSTudent** [Dekunutter/CherryBlossomGrotto#12]
https://pastebin.com/gsUSQknA

**Comment by Dekunutter** [comment]
Thanks for sharing. This is a problem with villager trades being mapped over other mods. I should be able to push out a fix before the weekend.

**Comment by Dekunutter** [comment]
This (and another compatibility issue with BlueSkies 1.18.2) has been fixed. Thanks again for reporting
