### ISSUE TITLE
cherryblossomgrotto1.19 crash OmnaticSin

### ISSUE THREAD

**Issue by AlaricEngel** [Dekunutter/CherryBlossomGrotto#18]
Hello! OmnaticSin here, doing as promised lol
[cherryblossomgrottocrash1.19.txt](https://github.com/Dekunutter/CherryBlossomGrotto/files/9143905/cherryblossomgrottocrash1.19.txt)

I hope the file works. I'm new at this, so I apologize for any mistakes made.

**Comment by Dekunutter** [comment]
Thank you for bringing this to my attention. The issue you are having is to do with the version of Forge you have installed. The mod is built to be compatible with Forge 41.0.63, but recent updates to Forge for Minecraft 1.19 have made many mods incompatible with the newer Forge versions. I am now working on a fix to make the mod compatible with Forge 41.0.100 (the version you have installed in the provided log files).

**Comment by AlaricEngel** [comment]
Ohhhhh. Ok yeah that kinda makes sense. Lol! Thanks for looking into it. :D

**Comment by Dekunutter** [comment]
I'm going to close this issue since I just pushed a bunch of fixes that should hopefully resolve this issue. The new download should be approved on CurseForge in a few hours. Thanks again for the crash logs!

**Comment by AlaricEngel** [comment]
Awesome, thanks for the update! Take care, and stay safe.
