### ISSUE TITLE
Dedicated server crash on 1.19.2

### ISSUE THREAD

**Issue by complicitsalami** [Dekunutter/CherryBlossomGrotto#24]
Hey there!

Thanks for the great mod I have really been enjoying using it. On the new 1.19.2 versions it looks like the mod is crashing for servers. I have added the crash below: 

https://pastebin.com/hyNHCukS

**Comment by Dekunutter** [comment]
Awesome thank you, and sorry you hit this issue. Oof I forgot to test the 1.19 release on a server before I pushed up the changes. Its crashing cause I am registering the particle engine on both servers and clients though particles can only be handled on clients. Luckily a fix for this is really simple and I should have something pushed very soon

**Comment by Dekunutter** [comment]
This ended up being a really quick fix. I have released v0.5.8 on CurseForge and Modrinth. Tested it on my client and servers locally and seems to work well. You should see the new version available on each site in the coming hours.

Closing out this issue as resolved!
