### ISSUE TITLE
Server Initialization crash using 0.5.6 version with forge 41.1.0

### ISSUE THREAD

**Issue by noirtakumi** [Dekunutter/CherryBlossomGrotto#26]
Hello! 
i recently discovered your mod and fell in love with it

it runs on my single player but when i tried to run it on my server

I was hit by this crash while initializing it
Can you please fix it? 

here's the crash report

[crash-ParticleEngine for Invalid dist DEDICATED_SERVER.txt](https://github.com/Dekunutter/CherryBlossomGrotto/files/9446364/crash-ParticleEngine.for.Invalid.dist.DEDICATED_SERVER.txt)

Thank you!

**Comment by Dekunutter** [comment]
Hi, thanks for bringing this to my attention. This is a known issue with v0.5.6 below of the mod on Minecraft 1.19.2. Please try running your server with the latest version of the mod, it should fix the ParticleEngine issue!

If you still run into this problem, feel free to open a new issue! I'll keep an eye out!
Thanks
