### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Icarus-Dark-Crow** [Dekunutter/CherryBlossomGrotto#41]
I have all required mods, Forge, Geckolic, Terrablender, and the mods file itself, however when I open it all in minecraft, it just gives me an error and says that it cannot launch. 
![Screenshot (15)](https://user-images.githubusercontent.com/126841751/222618327-78b030cc-a75b-460f-b850-62a41af51b69.png)

**Comment by DePhoegon** [comment]
Still having the issue as well

**Comment by Dekunutter** [comment]
Hi, this issue was marked as closed so I didn't think this was an active issue. If you are still encountering this could you please open a new issue and let me know what version of the mod you are trying to run and attach a crash report. That way I should be able to help you out!
