### ISSUE TITLE
Maple Saplings and Maple Leaf aren't dropping

### ISSUE THREAD

**Issue by CRRCode** [Dekunutter/CherryBlossomGrotto#45]
I found the Maple Woods biome but the drop of Maple Sapling and Maple Leaf items is wrong, the leaf blocks of the Maple tree drop Cherry Blossom Saplings and Leaves instead of Maple's.

I have the latest mod version: 1.4.0 for 1.19.3 Minecraft.

**Comment by Dekunutter** [comment]
Hi, thanks for reporting this issue! I can definitely see that as being an issue since I think I forgot to test the item drops when I added that tree variant. I'll work on a fix as soon as I am able (might be a few days before I am next able to publish a change)

**Comment by Dekunutter** [comment]
Hi, I released a fix for this issue in v1.5.1 of the mod today. You should be able to find it on Modrinth or on CurseForge when it passes verification. Thanks again for reporting!

**Comment by CRRCode** [comment]
Great! I will wait for the release of 1.19.3 version to test it out. And thanks to you!

**Comment by Dekunutter** [comment]
No problem, the 1.19.3 version with the fix will be released tonight!
