### ISSUE TITLE
Stripped Maple Log: Maple Log cannot be peeled

### ISSUE THREAD

**Issue by CRRCode** [Dekunutter/CherryBlossomGrotto#46]
I tried to peel a Maple Log with an axe and couldn't. It shows no reaction, so Stripped Maple Log is unobtainable.

**Comment by Dekunutter** [comment]
Hi, thanks for reporting this issue! I forgot to add the new log and wood blocks to the mappings for strippable items. Axes should now be able to strip maple logs and wood blocks. Stripped logs can then be right-clicked while holding a bottle to gather some maple syrup. This can only be done once per log (there's currently no visual indication of this in the stripped log, I havent finished this biome yet).

This all should be doable in v1.5.1 of the mod!
Closing this issue as resolved but please let me know if you still encounter issues on the new version.

**Comment by CRRCode** [comment]
Perfect, I'll try it when the release of 1.19.3 version comes out. Thank you for your hard work!
