### ISSUE TITLE
World Generation Crash - Possible Conflict w/ Other Wolrdgen Mods

### ISSUE THREAD

**Issue by kenthehuman23** [Dekunutter/CherryBlossomGrotto#50]
Hello! As instructed, please find the 'Pastebin' link for the crash report generated when I tried to create a new world with both your mod and other worldgen mods simultaneously loaded:

https://pastebin.com/K7hefJi4

**Comment by Dekunutter** [comment]
Thank you for providing the information. Looks like its an incompatibility between my mod and Terralith. A mismatch in how a biome from each order their generated features. I'll look into this and see if I can snoop out what the troublesome feature is

**Comment by Dekunutter** [comment]
Looks like there are a few incompatibilities to work through. I've found at least one, but seems it'll probably take me a few days to find the time to get them all figured out. Will report back when I make more progress!

**Comment by Dekunutter** [comment]
Ended up finding the issues and addressed them. Will be pushing v1.7.1 to CurseForge and Modrinth tonight. Please let me know if you encounter any other issues!
